osx_image: xcode7.2
language: objective-c
xcode_workspace: org.onebusaway.iphone.xcworkspace
xcode_scheme:
    - Debug
xcode_sdk:
    - iphonesimulator
script:
  - xctool -workspace org.onebusaway.iphone.xcworkspace -scheme OneBusAway -sdk iphonesimulator -configuration Debug test -only OneBusAwayTests ONLY_ACTIVE_ARCH=NO
notifications:
  slack:
    rooms:
      - onebusaway:kcIbPpOOuJEhNgpzWMd8gkqj
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30e6e2d8791d3099cbe5
    on_success: always
    on_failure: always
    on_start: true
